# Generated by Django 3.0.8 on 2020-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.IntegerField(default=7),
        ),
    ]
