# Generated by Django 3.0.8 on 2020-07-20 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_db', '0003_auto_20200720_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='difficulty_index',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
