# Generated by Django 3.0.8 on 2020-07-20 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_db', '0004_level_difficulty_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty_index',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
