# Generated by Django 3.0.8 on 2020-07-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_db', '0005_auto_20200720_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('answe', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_db.Topic')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_db.Level')),
            ],
        ),
    ]
