# Generated by Django 3.0.8 on 2020-07-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_db', '0007_auto_20200720_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='answe',
            new_name='answer',
        ),
    ]
